"""followers

Revision ID: 86481d0105f0
Revises: c027a2882a87
Create Date: 2024-02-20 15:22:34.403918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86481d0105f0'
down_revision = 'c027a2882a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
